name: Build exe with PyInstaller and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build exe (PyInstaller -D)
      run: pyinstaller -D --console -n VideoCompressor ./vcmain/main.py -y

    - name: Rename and Archive artifacts
      run: |
        mv dist/VideoCompressor dist/VideoCompressor-Portable
        zip -r dist/VideoCompressor.zip dist/VideoCompressor-Portable
      shell: bash
    - name: Archive Portable artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts-portable
        path: dist/VideoCompressor.zip

    - name: Build exe (PyInstaller -F)
      run: pyinstaller -F --console -n VideoCompressor ./vcmain/main.py -y

    - name: Rename and Archive artifacts
      run: |
        mv dist/VideoCompressor.exe dist/VideoCompressor-Portable.exe
      shell: bash
    - name: Archive Portable exe artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts-portable
        path: dist/VideoCompressor-Portable.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: Release ${{ github.ref }}

    - name: Upload Release Asset (Portable)
      id: upload_release_asset_portable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/VideoCompressor-Portable.exe
        asset_name: VideoCompressor-Portable.exe
        asset_content_type: application/octet-stream

    - name: Upload Release Asset (Zip)
      id: upload_release_asset_zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/VideoCompressor.zip
        asset_name: VideoCompressor.zip
        asset_content_type: application/zip
